# docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aurora_api_core
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=aurora_db_2
      - DB_USERNAME=DB_AURORA_CORE
      - DB_PASSWORD=aurora123
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: aurora_db_core
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: aurora_db_2
      MYSQL_USER: DB_AURORA_CORE
      MYSQL_PASSWORD: aurora123
      MYSQL_ROOT_PASSWORD: aurora123
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
